version: '2'

services:
  db:
    image: mysql
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_user_password
    volumes:
      - db:/var/lib/mysql:rw
    networks:
      - default
    dns_search:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 80
    links:
        - db
  
  php:
    build: php7-fpm
    ports:
      - 9000
    links:
      - db:mysqldb
    volumes:
      - chemin/vers/votre/app/symfony:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/app/logs
    networks:
      - default
    dns_search:
      - php
  
  front:
    image: nginx
    ports:
      - 80
    volumes:
      - .:/home/docker:ro
      - ./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
  
  engine:
    build: ./docker/engine/
    volumes:
      - .:/home/docker:rw
      - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    working_dir: /home/docker
    networks:
      - default
    dns_search:
      - engine

  elk:
    image: willdurand/elk
    ports:
      - 80
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
      - php
      - nginx
   networks:
      - default
    dns_search:
      - engine



volumes:
  db: {}
networks:
  default: {}