parameters:
    my_user_provider.class: Masta\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    masta_user.password_resetting:
        class: Masta\UserBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    masta_user.form.registration:
        class: Masta\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: masta_user_registration }

    masta_user.form.profile:
        class: Masta\UserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: masta_user_profile }

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
    
    masta_plateforme.oauth_event_listener:
      class: Masta\UserBundle\EventListener\OAuthEventListener
      tags:
          - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }
          - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }
