<?php

namespace Masta\PlateFormeBundle\Repository\Deal;

use Doctrine\ORM\EntityRepository;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
  //get Messages by conversation
  public function getMessagesConversation($limit, $page,$conversation_id,$user){

    $queryBuilder = $this->createQueryBuilder('cr')
                         ->where('cr.conversation =:conversation_id')->setParameter('conversation_id', $conversation_id)
                         ->orderBy('cr.publishedAt', 'DESC')
                         ->getQuery();
    $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
    $pager = new Pagerfanta($pagerAdapter);
    $pager->setMaxPerPage($limit);
    
    //ceci est temporaire
    //$last_page = $pager->getNbPages();
    
    $pager->setCurrentPage($page);
  
    return $pager;
  }
}
