<?php

namespace Masta\PlateFormeBundle\Repository\Album;
use Doctrine\ORM\EntityRepository;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * AlbumFollowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumFollowerRepository extends EntityRepository
{
    public function getAlbumFollowers($limit, $page, $album_id)
    {
        $queryBuilder = $this->createQueryBuilder('af')
            ->leftJoin('af.album', 'a')->addSelect('a')
            ->where('a.id = :album_id')->setParameter('album_id', $album_id)
            ->orderBy('af.publishedAt', 'DESC')
            ->getQuery();
        $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
        $pager = new Pagerfanta($pagerAdapter);
        $pager->setCurrentPage($page);
        $pager->setMaxPerPage($limit);

        return $pager;
    }
}
