#BASE ROUTE
masta_core:
    resource: "@MastaCoreBundle/Resources/config/routing.yml"
    prefix:   /

#REST ROUTE
rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  options:
      expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin


