<?php

namespace Masta\UserBundle\Repository;

use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountries($limit, $page)
    {
        $queryBuilder = $this->createQueryBuilder('c')
                             ->where('c.nbCities > :zero')->setParameter('zero', 0) 
                             ->orderBy('c.rank', 'DESC')
                             ->getQuery();
        $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
        $pager = new Pagerfanta($pagerAdapter);
        $pager->setMaxPerPage($limit);
        $pager->setCurrentPage($page);
    
        return $pager;
    }
}
