<?php

namespace Masta\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsers($limit, $page)
    {
        $queryBuilder = $this->createQueryBuilder('u')->getQuery();
        $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
        $pager = new Pagerfanta($pagerAdapter);
        $pager->setCurrentPage($page);
        $pager->setMaxPerPage($limit);

        return $pager;
    }

    public function getSuggestions($limit, $page, $user)
    {
        $follows_id = null;
        foreach ($user->getFollows() as $uf) $follows_id[] = $uf->getUserFollowed()->getId();
        $categoryFollows= array(); 
        foreach ($user->getCategoryFollows() as $cf) $categoryFollows[] = $cf->getCategory();
        $city = $user->getCity();
        $country = $user->getCountry();

          $qb = $this->createQueryBuilder('u')
                               //->leftJoin('u.categoryFollows', 'cf')->addSelect('cf')
                               //->andWhere('cf.category in(:categoryFollows)')->setParameter('categoryFollows', $categoryFollows)
                               ->where('u.city =:city')->setParameter('city', $city)
                               ->orWhere('u.country =:country')->setParameter('country', $country)
                               ->andWhere('u.id <> :id')->setParameter('id', $user->getId());
          if($follows_id != null)  $qb->andWhere('u.id not in(:follows_id)')->setParameter('follows_id', $follows_id);
         
          $qb->getQuery();

        $pagerAdapter = new DoctrineORMAdapter($qb);
        $pager = new Pagerfanta($pagerAdapter);
        $pager->setCurrentPage($page);
        $pager->setMaxPerPage($limit);

        return $pager;
    }
}
