<?php

namespace Masta\PlateFormeBundle\Repository\Notification;

use Doctrine\ORM\EntityRepository;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function getNotifications($limit, $page)
    {
        $queryBuilder = $this->createQueryBuilder('n')
            ->orderBy('n.publishedAt', 'DESC')
            ->getQuery();
        $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
        $pager = new Pagerfanta($pagerAdapter);
        $pager->setMaxPerPage($limit);
        $pager->setCurrentPage($page);


        return $pager;
    }

    public function getMyNotifications($limit, $page, $user){
      $queryBuilder = $this->createQueryBuilder('n')
                            ->where('n.destinator =:user')->setParameter('user', $user)
                            ->orderBy('n.publishedAt', 'DESC')
                            ->getQuery();
      $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
      $pager = new Pagerfanta($pagerAdapter);
      $pager->setMaxPerPage($limit);
      $pager->setCurrentPage($page);


      return $pager;
    }
}
