Masta\PlateFormeBundle\Entity\Deal\Message:
    exclusion_policy: ALL
    properties :
        id :
            expose : true
        content:
            expose : true
        publishedAt:
            expose : true
        isSeen :
            expose : true
        author :
            expose : true
        isAuthor :
            expose : true