Masta\PlateFormeBundle\Entity\Category\Category:
    exclusion_policy: ALL
    properties :
        id :
            expose : true
        name :
            expose : true
        picture: 
            
        publishedAt:
            expose : true
        nbProducts :
            expose : true
        nbFollowers :
            expose : true
        isFollow:
            expose : true
        isAuthent:
            expose : true
