<?php

namespace Masta\PlateFormeBundle\Hashtag\Repository;

use Doctrine\ORM\EntityRepository;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * HashtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashtagRepository extends EntityRepository
{
    public function getHashtags($limit, $page)
    {
        $queryBuilder = $this->createQueryBuilder('h')
            ->orderBy('h.id', 'DESC')
            ->getQuery();
        $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
        $pager = new Pagerfanta($pagerAdapter);
        $pager->setCurrentPage($page);
        $pager->setMaxPerPage($limit);

        return $pager;
    }
}
