<?php

namespace Masta\PlateFormeBundle\Repository\Category;

use Doctrine\ORM\EntityRepository;

use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategories($limit, $page)
    {
        $queryBuilder = $this->createQueryBuilder('c')
                             ->orderBy('c.publishedAt', 'DESC')
                             ->where('c.isPublished = true')
                             ->orderBy('c.rank', 'DESC')
                             ->getQuery();
        $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
        $pager = new Pagerfanta($pagerAdapter);
        $pager->setCurrentPage($page);
        $pager->setMaxPerPage($limit);

        return $pager;
    }

    public function getCategoriesFollowByUser($limit, $page,$user)
    {
         $queryBuilder = $this->createQueryBuilder('c')
                              ->leftJoin('c.categoryFollowers', 'f')->addSelect('f')
        					  ->where('f.author = :author')->setParameter('author', $user)
                              ->orderBy('c.publishedAt', 'DESC')
                              ->andWhere('c.isPublished = true')
                              ->getQuery();
        $pagerAdapter = new DoctrineORMAdapter($queryBuilder);
        $pager = new Pagerfanta($pagerAdapter);
        $pager->setMaxPerPage($limit);
        $pager->setCurrentPage($page);
        

        return $pager;
    }
}
